// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUr4HrUiHiKjv2fcDoza_7xZuX0IMAZCY',
    appId: '1:276251446691:web:efe22db7a5302509959e16',
    messagingSenderId: '276251446691',
    projectId: 'tilang-app',
    authDomain: 'tilang-app.firebaseapp.com',
    storageBucket: 'tilang-app.firebasestorage.app',
    measurementId: 'G-L3LDGVPT42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACf3Mhs-YU37PjnmtKP2o4DbOayTL-nGI',
    appId: '1:276251446691:android:732070f47d7abcc1959e16',
    messagingSenderId: '276251446691',
    projectId: 'tilang-app',
    storageBucket: 'tilang-app.firebasestorage.app',
  );
}
